export const botsList = [
    { name: 'Helen', img: 'fe0000.jpg' },
    { name: 'July', img: 'fe0001.jpg' },
    { name: 'Anna', img: 'fe0002.jpg' },
    { name: 'Sophia', img: 'fe0003.jpg' },
    { name: 'Emma', img: 'fe0004.jpg' },
    { name: 'Olivia', img: 'fe0005.jpg' },
    { name: 'Mia', img: 'fe0006.jpg' },
    { name: 'Lily', img: 'fe0007.jpg' },
    { name: 'Max', img: 'fe0008.jpg' },
    { name: 'Amelia', img: 'fe0009.jpg' },
    { name: 'Isabella', img: 'fe0010.jpg' },

    { name: 'Peter', img: 'ma0000.jpg' },
    { name: 'Brian', img: 'ma0001.jpg' },
    { name: 'John', img: 'ma0002.jpg' },
    { name: 'James', img: 'ma0003.jpg' },
    { name: 'Michael', img: 'ma0004.jpg' },
    { name: 'David', img: 'ma0005.jpg' },
    { name: 'Chris', img: 'ma0006.jpg' },
    { name: 'Mark', img: 'ma0007.jpg' },
    { name: 'William', img: 'ma0008.jpg' },
    { name: 'Lucas', img: 'ma0009.jpg' },
    { name: 'Ethan', img: 'ma0010.jpg' }
]